spring:
  application:
    name: Timesheet-Wizard
  main:
    web-application-type: none

jackson:
  serialization:
    writeDatesAsTimestamps: false

timesheet-wizard:
  azure:
    blob:
      container: tw-sheets
  import:
    clockify:
      reports-url: "https://reports.api.clockify.me/"
      api-key: ${CLOCKIFY_API_KEY}
      workspace-id: ${CLOCKIFY_WORKSPACE_ID}

logging:
  level:
    dev.hertlein.timesheetwizard: DEBUG
